/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.brane08.pagila;

import org.junit.jupiter.api.Test;

class JettyServerTest {
    @Test
    void appHasAGreeting() {
    }
}
