ktor:
  development: true
  application:
    modules:
      - com.github.brane08.pagila.ApplicationKt.module
  deployment:
    port: 8001
    watch:
      - classes
database:
  url: "jdbc:postgresql://localhost:5432/sakila"
  driverClass: org.postgresql.Driver
  user: postgres
  password: ""
