# Configuration
play.modules.enabled += "com.github.brane08.pagila.seedworks.infra.MappersModule"

play.evolutions.db.default.enabled = false

# Assets configuration
"assets.cache./public/stylesheets/bootstrap.min.css" = "max-age=3600"

# Number of database connections
fixedConnectionPool = 10

db.default {
  driver = org.postgresql.Driver
  url = "jdbc:postgresql://localhost:5432/pagila?currentSchema=public"
  username = "postgres"
  password = ""

  jndiName = PagilaDS
}

jpa.default = PagilaPU

play.db {
  prototype {
    hikaricp.minimumIdle = ${fixedConnectionPool}
    hikaricp.maximumPoolSize = ${fixedConnectionPool}
  }
}

# Job queue sized to HikariCP connection pool
database.dispatcher {
  executor = "thread-pool-executor"
  throughput = 1
  thread-pool-executor {
    fixed-pool-size = ${fixedConnectionPool}
  }
}
