quarkus.banner.enabled=false
quarkus.http.port=8081
# datasource properties
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/sakila
quarkus.datasource.jdbc.max-size=7
quarkus.package.type=fast-jar
quarkus.qute.content-types.ts-html=text/vnd.turbo-stream.html
# logging properties
quarkus.log.category."io.ebean.SQL".level=debug
